version: '3'

services:

  web:
    image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/django-ecs-web:latest
    command: sh /code/run-my-app.sh 

  nginx :
    image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/django-ecs-nginx:latest
    ports:
      - "80:80"
    links:
      - web