version: '3'

services:

  web:
    image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/django-ecs-web:latest
    ports:
      - "8001:8001"

  nginx :
    image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/django-ecs-nginx:latest
    ports:
      - "80:80"
    links:
      - web