FROM python:3.8-slim

RUN apt update && apt install -y --no-install-recommends \
    gcc \
    libc-dev \
    python3-pip --upgrade pip \
    && apt-get clean

COPY ./web/requirements.txt /code/
RUN pip3 install -r /code/requirements.txt \
    && pip3 install uwsgi

COPY ./src/ /code/

# 8001番ポートを開放する
EXPOSE 8001
# 作業用フォルダを /code/ にする
WORKDIR /code/

RUN mkdir /var/log/uwsgi/

ENTRYPOINT ["uwsgi"]
CMD ["--ini","/code/config/config/uwsgi.ini"]